services:
  - type: web
    name: bi-dashboard
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --config gunicorn_config.py server:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: DATABASE_URL
        value: postgresql://bi_dashboard_user:Y4CJcOwpda7FBq1IvXxZViic8o52wS6h@dpg-d0um76re5dus739m2ang-a.oregon-postgres.render.com/bi_dashboard_bpft 